In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
temperature = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/temperature_iso3.csv')

In [ ]:
temperature.head()

   year        AFG        ALB        DZA  ...        ZMB        ZWE       ROU  SCG
0  1901  13.096678  10.832000  22.460234  ...  21.574623  21.239357  9.215595  NaN
1  1902  13.309858  11.086333  22.517385  ...  21.753736  21.546436  8.389345  NaN
2  1903  12.064352  11.235000  22.276083  ...  21.885994  21.726206  9.500536  NaN
3  1904  12.619226  11.242333  22.407259  ...  21.323898  20.781176  8.901487  NaN
4  1905  12.437119  11.009000  22.348454  ...  21.760672  21.535593  9.126190  NaN

[5 rows x 242 columns]

In [ ]:
countries = temperature.columns[1:]

In [ ]:
# convert dataframe to have year, iso as columns
temperature = pd.melt(temperature, id_vars=['year'], value_vars=countries, var_name='iso', value_name='temperature')

In [ ]:
# need to add country names 
country_codes = [{'id': 466, 'iso2': 'AF', 'iso3': 'AFG', 'name': 'Afghanistan'},
 {'id': 582, 'iso2': 'AL', 'iso3': 'ALB', 'name': 'Albania'},
 {'id': 520, 'iso2': 'DZ', 'iso3': 'DZA', 'name': 'Algeria'},
 {'id': 677, 'iso2': 'AS', 'iso3': 'ASM', 'name': 'American Samoa (U.S.)'},
 {'id': 675, 'iso2': 'AD', 'iso3': 'AND', 'name': 'Andorra'},
 {'id': 544, 'iso2': 'AO', 'iso3': 'AGO', 'name': 'Angola'},
 {'id': 716, 'iso2': 'AI', 'iso3': 'AIA', 'name': 'Anguilla (U.K.)'},
 {'id': 583, 'iso2': 'AG', 'iso3': 'ATG', 'name': 'Antigua and Barbuda'},
 {'id': 563, 'iso2': 'AR', 'iso3': 'ARG', 'name': 'Argentina'},
 {'id': 584, 'iso2': 'AM', 'iso3': 'ARM', 'name': 'Armenia'},
 {'id': 674, 'iso2': 'AW', 'iso3': 'ABW', 'name': 'Aruba (Neth.)'},
 {'id': 585, 'iso2': 'AU', 'iso3': 'AUS', 'name': 'Australia'},
 {'id': 586, 'iso2': 'AT', 'iso3': 'AUT', 'name': 'Austria'},
 {'id': 491, 'iso2': 'AZ', 'iso3': 'AZE', 'name': 'Azerbaijan'},
 {'id': 587, 'iso2': 'BS', 'iso3': 'BHS', 'name': 'Bahamas, The'},
 {'id': 588, 'iso2': 'BH', 'iso3': 'BHR', 'name': 'Bahrain'},
 {'id': 469, 'iso2': 'BD', 'iso3': 'BGD', 'name': 'Bangladesh'},
 {'id': 589, 'iso2': 'BB', 'iso3': 'BRB', 'name': 'Barbados'},
 {'id': 590, 'iso2': 'BY', 'iso3': 'BLR', 'name': 'Belarus'},
 {'id': 591, 'iso2': 'BE', 'iso3': 'BEL', 'name': 'Belgium'},
 {'id': 576, 'iso2': 'BZ', 'iso3': 'BLZ', 'name': 'Belize'},
 {'id': 551, 'iso2': 'BJ', 'iso3': 'BEN', 'name': 'Benin'},
 {'id': 679, 'iso2': 'BM', 'iso3': 'BMU', 'name': 'Bermuda (U.K.)'},
 {'id': 467, 'iso2': 'BT', 'iso3': 'BTN', 'name': 'Bhutan'},
 {'id': 561, 'iso2': 'BO', 'iso3': 'BOL', 'name': 'Bolivia'},
 {'id': 678, 'iso2': 'BA', 'iso3': 'BIH', 'name': 'Bosnia and Herzegovina'},
 {'id': 542, 'iso2': 'BW', 'iso3': 'BWA', 'name': 'Botswana'},
 {'id': 569, 'iso2': 'BR', 'iso3': 'BRA', 'name': 'Brazil'},
 {'id': 720,
  'iso2': 'IO',
  'iso3': 'IOT',
  'name': 'British Indian Ocean Territory (U.K.)'},
 {'id': 717,
  'iso2': 'VG',
  'iso3': 'VGB',
  'name': 'British Virgin Islands (U.K.)'},
 {'id': 592, 'iso2': 'BN', 'iso3': 'BRN', 'name': 'Brunei'},
 {'id': 497, 'iso2': 'BG', 'iso3': 'BGR', 'name': 'Bulgaria'},
 {'id': 552, 'iso2': 'BF', 'iso3': 'BFA', 'name': 'Burkina Faso'},
 {'id': 593, 'iso2': 'BI', 'iso3': 'BDI', 'name': 'Burundi'},
 {'id': 478, 'iso2': 'KH', 'iso3': 'KHM', 'name': 'Cambodia'},
 {'id': 548, 'iso2': 'CM', 'iso3': 'CMR', 'name': 'Cameroon'},
 {'id': 594, 'iso2': 'CA', 'iso3': 'CAN', 'name': 'Canada'},
 {'id': 595, 'iso2': 'CV', 'iso3': 'CPV', 'name': 'Cape Verde'},
 {'id': 680, 'iso2': 'KY', 'iso3': 'CYM', 'name': 'Cayman Islands (U.K.)'},
 {'id': 528, 'iso2': 'CF', 'iso3': 'CAF', 'name': 'Central African Republic'},
 {'id': 524, 'iso2': 'TD', 'iso3': 'TCD', 'name': 'Chad'},
 {'id': 562, 'iso2': 'CL', 'iso3': 'CHL', 'name': 'Chile'},
 {'id': 473, 'iso2': 'CN', 'iso3': 'CHN', 'name': 'China'},
 {'id': 721, 'iso3': 'CXR', 'name': 'Christmas Island (Aus.)'},
 {'id': 722, 'iso3': 'CCK', 'name': 'Cocos (Keeling) Islands (Aus.)'},
 {'id': 565, 'iso2': 'CO', 'iso3': 'COL', 'name': 'Colombia'},
 {'id': 598, 'iso2': 'KM', 'iso3': 'COM', 'name': 'Comoros'},
 {'id': 547, 'iso2': 'CG', 'iso3': 'COG', 'name': 'Congo'},
 {'id': 712, 'iso3': 'COD', 'name': 'Congo, Democratic Republic of'},
 {'id': 600, 'iso2': 'CK', 'iso3': 'COK', 'name': 'Cook Islands (N.Z.)'},
 {'id': 579, 'iso2': 'CR', 'iso3': 'CRI', 'name': 'Costa Rica'},
 {'id': 671, 'iso2': 'CI', 'iso3': 'CIV', 'name': "Cote d'Ivoire"},
 {'id': 501, 'iso2': 'HR', 'iso3': 'HRV', 'name': 'Croatia'},
 {'id': 574, 'iso2': 'CU', 'iso3': 'CUB', 'name': 'Cuba'},
 {'id': 601, 'iso2': 'CY', 'iso3': 'CYP', 'name': 'Cyprus'},
 {'id': 681, 'iso2': 'CZ', 'iso3': 'CZE', 'name': 'Czech Republic'},
 {'id': 603, 'iso2': 'DK', 'iso3': 'DNK', 'name': 'Denmark'},
 {'id': 715, 'iso3': 'XXX', 'name': 'Disputed Area - China and India'},
 {'id': 523, 'iso2': 'DJ', 'iso3': 'DJI', 'name': 'Djibouti'},
 {'id': 604, 'iso2': 'DM', 'iso3': 'DMA', 'name': 'Dominica'},
 {'id': 605, 'iso2': 'DO', 'iso3': 'DOM', 'name': 'Dominican Republic'},
 {'id': 564, 'iso2': 'EC', 'iso3': 'ECU', 'name': 'Ecuador'},
 {'id': 514, 'iso2': 'EG', 'iso3': 'EGY', 'name': 'Egypt, Arab Republic of'},
 {'id': 581, 'iso2': 'SV', 'iso3': 'SLV', 'name': 'El Salvador'},
 {'id': 550, 'iso2': 'GQ', 'iso3': 'GNQ', 'name': 'Equatorial Guinea'},
 {'id': 531, 'iso2': 'ER', 'iso3': 'ERI', 'name': 'Eritrea'},
 {'id': 606, 'iso2': 'EE', 'iso3': 'EST', 'name': 'Estonia'},
 {'id': 532, 'iso2': 'ET', 'iso3': 'ETH', 'name': 'Ethiopia'},
 {'id': 730,
  'iso2': 'FK',
  'iso3': 'FLK',
  'name': 'Falkland Islands (U.K.) / (Islas Malvina'},
 {'id': 682, 'iso2': 'FO', 'iso3': 'FRO', 'name': 'Faroe Islands (Den.)'},
 {'id': 483, 'iso2': 'FJ', 'iso3': 'FJI', 'name': 'Fiji'},
 {'id': 607, 'iso2': 'FI', 'iso3': 'FIN', 'name': 'Finland'},
 {'id': 706, 'iso2': 'EH', 'iso3': 'ESH', 'name': 'Former Spanish Sahara'},
 {'id': 608, 'iso2': 'FR', 'iso3': 'FRA', 'name': 'France'},
 {'id': 687, 'iso3': 'GUF', 'name': 'French Guiana (Fr.)'},
 {'id': 702, 'iso2': 'PF', 'iso3': 'PYF', 'name': 'French Polynesia (Fr.)'},
 {'id': 549, 'iso2': 'GA', 'iso3': 'GAB', 'name': 'Gabon'},
 {'id': 609, 'iso2': 'GM', 'iso3': 'GMB', 'name': 'Gambia, The'},
 {'id': 492, 'iso2': 'GE', 'iso3': 'GEO', 'name': 'Georgia'},
 {'id': 610, 'iso2': 'DE', 'iso3': 'DEU', 'name': 'Germany'},
 {'id': 556, 'iso2': 'GH', 'iso3': 'GHA', 'name': 'Ghana'},
 {'id': 684, 'iso2': 'GI', 'iso3': 'GIB', 'name': 'Gibraltar (U.K.)'},
 {'id': 729, 'iso3': 'ATF', 'name': 'Glorioso Islands (Fr.)'},
 {'id': 611, 'iso2': 'GR', 'iso3': 'GRC', 'name': 'Greece'},
 {'id': 686, 'iso2': 'GL', 'iso3': 'GRL', 'name': 'Greenland (Den.)'},
 {'id': 612, 'iso2': 'GD', 'iso3': 'GRD', 'name': 'Grenada'},
 {'id': 685, 'iso2': 'GP', 'iso3': 'GLP', 'name': 'Guadeloupe (Fr.)'},
 {'id': 688, 'iso2': 'GU', 'iso3': 'GUM', 'name': 'Guam (U.S.)'},
 {'id': 575, 'iso2': 'GT', 'iso3': 'GTM', 'name': 'Guatemala'},
 {'id': 732, 'iso2': 'GG', 'iso3': 'GGY', 'name': 'Guernsey (U.K.)'},
 {'id': 554, 'iso2': 'GN', 'iso3': 'GIN', 'name': 'Guinea'},
 {'id': 613, 'iso2': 'GW', 'iso3': 'GNB', 'name': 'Guinea-Bissau'},
 {'id': 567, 'iso2': 'GY', 'iso3': 'GUY', 'name': 'Guyana'},
 {'id': 614, 'iso2': 'HT', 'iso3': 'HTI', 'name': 'Haiti'},
 {'id': 577, 'iso2': 'HN', 'iso3': 'HND', 'name': 'Honduras'},
 {'id': 689, 'iso3': 'HKG', 'name': 'Hongkong'},
 {'id': 502, 'iso2': 'HU', 'iso3': 'HUN', 'name': 'Hungary'},
 {'id': 615, 'iso2': 'IS', 'iso3': 'ISL', 'name': 'Iceland'},
 {'id': 468, 'iso2': 'IN', 'iso3': 'IND', 'name': 'India'},
 {'id': 482, 'iso2': 'ID', 'iso3': 'IDN', 'name': 'Indonesia'},
 {'id': 508, 'iso2': 'IR', 'iso3': 'IRN', 'name': 'Iran'},
 {'id': 509, 'iso2': 'IQ', 'iso3': 'IRQ', 'name': 'Iraq'},
 {'id': 617, 'iso2': 'IE', 'iso3': 'IRL', 'name': 'Ireland'},
 {'id': 690, 'iso2': 'IM', 'iso3': 'IMN', 'name': 'Isle of Man (U.K.)'},
 {'id': 618, 'iso2': 'IL', 'iso3': 'ISR', 'name': 'Israel'},
 {'id': 619, 'iso2': 'IT', 'iso3': 'ITA', 'name': 'Italy'},
 {'id': 620, 'iso2': 'JM', 'iso3': 'JAM', 'name': 'Jamaica'},
 {'id': 621, 'iso2': 'JP', 'iso3': 'JPN', 'name': 'Japan'},
 {'id': 733, 'iso2': 'JE', 'iso3': 'JEY', 'name': 'Jersey (U.K.)'},
 {'id': 513, 'iso2': 'JO', 'iso3': 'JOR', 'name': 'Jordan'},
 {'id': 487, 'iso2': 'KZ', 'iso3': 'KAZ', 'name': 'Kazakhstan'},
 {'id': 534, 'iso2': 'KE', 'iso3': 'KEN', 'name': 'Kenya'},
 {'id': 622, 'iso2': 'KI', 'iso3': 'KIR', 'name': 'Kiribati'},
 {'id': 475,
  'iso2': 'KP',
  'iso3': 'PRK',
  'name': 'Korea, Democratic Peoples Republic of'},
 {'id': 623, 'iso2': 'KR', 'iso3': 'KOR', 'name': 'Korea, Republic of'},
 {'id': 714, 'iso3': 'XRK', 'name': 'Kosovo'},
 {'id': 624, 'iso2': 'KW', 'iso3': 'KWT', 'name': 'Kuwait'},
 {'id': 625, 'iso2': 'KG', 'iso3': 'KGZ', 'name': 'Kyrgyz Republic'},
 {'id': 479,
  'iso2': 'LA',
  'iso3': 'LAO',
  'name': "Lao, People's Democratic Republic of"},
 {'id': 507, 'iso2': 'LV', 'iso3': 'LVA', 'name': 'Latvia'},
 {'id': 517, 'iso2': 'LB', 'iso3': 'LBN', 'name': 'Lebanon'},
 {'id': 627, 'iso2': 'LS', 'iso3': 'LSO', 'name': 'Lesotho'},
 {'id': 557, 'iso2': 'LR', 'iso3': 'LBR', 'name': 'Liberia'},
 {'id': 519, 'iso2': 'LY', 'iso3': 'LBY', 'name': 'Libya'},
 {'id': 692, 'iso2': 'LI', 'iso3': 'LIE', 'name': 'Liechtenstein'},
 {'id': 506, 'iso2': 'LT', 'iso3': 'LTU', 'name': 'Lithuania'},
 {'id': 629, 'iso2': 'LU', 'iso3': 'LUX', 'name': 'Luxembourg'},
 {'id': 693, 'iso2': 'MO', 'iso3': 'MAC', 'name': 'Macao'},
 {'id': 630, 'iso2': 'MK', 'iso3': 'MKD', 'name': 'Macedonia, FYR'},
 {'id': 538, 'iso2': 'MG', 'iso3': 'MDG', 'name': 'Madagascar'},
 {'id': 539, 'iso2': 'MW', 'iso3': 'MWI', 'name': 'Malawi'},
 {'id': 481, 'iso2': 'MY', 'iso3': 'MYS', 'name': 'Malaysia'},
 {'id': 631, 'iso2': 'MV', 'iso3': 'MDV', 'name': 'Maldives'},
 {'id': 529, 'iso2': 'ML', 'iso3': 'MLI', 'name': 'Mali'},
 {'id': 632, 'iso2': 'MT', 'iso3': 'MLT', 'name': 'Malta'},
 {'id': 695, 'iso2': 'MH', 'iso3': 'MHL', 'name': 'Marshall Islands'},
 {'id': 698, 'iso2': 'MQ', 'iso3': 'MTQ', 'name': 'Martinique (Fr.)'},
 {'id': 530, 'iso2': 'MR', 'iso3': 'MRT', 'name': 'Mauritania'},
 {'id': 633, 'iso2': 'MU', 'iso3': 'MUS', 'name': 'Mauritius'},
 {'id': 699, 'iso2': 'YT', 'iso3': 'MYT', 'name': 'Mayotte (Fr.)'},
 {'id': 572, 'iso2': 'MX', 'iso3': 'MEX', 'name': 'Mexico'},
 {'id': 683,
  'iso2': 'FM',
  'iso3': 'FSM',
  'name': 'Micronesia, Federated States of'},
 {'id': 495, 'iso2': 'MD', 'iso3': 'MDA', 'name': 'Moldova'},
 {'id': 694, 'iso2': 'MC', 'iso3': 'MCO', 'name': 'Monaco'},
 {'id': 474, 'iso2': 'MN', 'iso3': 'MNG', 'name': 'Mongolia'},
 {'id': 697, 'iso2': 'ME', 'iso3': 'MNE', 'name': 'Montenegro'},
 {'id': 718, 'iso3': 'MSR', 'name': 'Montserrat (U.K.)'},
 {'id': 521, 'iso2': 'MA', 'iso3': 'MAR', 'name': 'Morocco'},
 {'id': 537, 'iso2': 'MZ', 'iso3': 'MOZ', 'name': 'Mozambique'},
 {'id': 472, 'iso2': 'MM', 'iso3': 'MMR', 'name': 'Myanmar'},
 {'id': 543, 'iso2': 'NA', 'iso3': 'NAM', 'name': 'Namibia'},
 {'id': 636, 'iso2': 'NR', 'iso3': 'NRU', 'name': 'Nauru'},
 {'id': 470, 'iso2': 'NP', 'iso3': 'NPL', 'name': 'Nepal'},
 {'id': 676, 'iso3': 'ANT', 'name': 'Netherlands Antilles (Neth.)'},
 {'id': 637, 'iso2': 'NL', 'iso3': 'NLD', 'name': 'Netherlands, The'},
 {'id': 700, 'iso2': 'NC', 'iso3': 'NCL', 'name': 'New Caledonia (Fr.)'},
 {'id': 638, 'iso2': 'NZ', 'iso3': 'NZL', 'name': 'New Zealand'},
 {'id': 578, 'iso2': 'NI', 'iso3': 'NIC', 'name': 'Nicaragua'},
 {'id': 525, 'iso2': 'NE', 'iso3': 'NER', 'name': 'Niger'},
 {'id': 527, 'iso2': 'NG', 'iso3': 'NGA', 'name': 'Nigeria'},
 {'id': 639, 'iso2': 'NU', 'iso3': 'NIU', 'name': 'Niue (N.Z.)'},
 {'id': 728, 'iso2': 'NF', 'iso3': 'NFK', 'name': 'Norfolk Island (Aus.)'},
 {'id': 696,
  'iso2': 'MP',
  'iso3': 'MNP',
  'name': 'Northern Mariana Islands (U.S.)'},
 {'id': 640, 'iso2': 'NO', 'iso3': 'NOR', 'name': 'Norway'},
 {'id': 511, 'iso2': 'OM', 'iso3': 'OMN', 'name': 'Oman'},
 {'id': 465, 'iso2': 'PK', 'iso3': 'PAK', 'name': 'Pakistan'},
 {'id': 641, 'iso2': 'PW', 'iso3': 'PLW', 'name': 'Palau'},
 {'id': 580, 'iso2': 'PA', 'iso3': 'PAN', 'name': 'Panama'},
 {'id': 485, 'iso2': 'PG', 'iso3': 'PNG', 'name': 'Papua New Guinea'},
 {'id': 571, 'iso2': 'PY', 'iso3': 'PRY', 'name': 'Paraguay'},
 {'id': 560, 'iso2': 'PE', 'iso3': 'PER', 'name': 'Peru'},
 {'id': 484, 'iso2': 'PH', 'iso3': 'PHL', 'name': 'Philippines'},
 {'id': 727, 'iso2': 'PN', 'iso3': 'PCN', 'name': 'Pitcairn Islands (U.K.)'},
 {'id': 505, 'iso2': 'PL', 'iso3': 'POL', 'name': 'Poland'},
 {'id': 642, 'iso2': 'PT', 'iso3': 'PRT', 'name': 'Portugal'},
 {'id': 701, 'iso2': 'PR', 'iso3': 'PRI', 'name': 'Puerto Rico (U.S.)'},
 {'id': 643, 'iso2': 'QA', 'iso3': 'QAT', 'name': 'Qatar'},
 {'id': 704, 'iso3': 'ROM', 'name': 'Romania'},
 {'id': 488, 'iso2': 'RU', 'iso3': 'RUS', 'name': 'Russia'},
 {'id': 645, 'iso2': 'RW', 'iso3': 'RWA', 'name': 'Rwanda'},
 {'id': 703, 'iso2': 'RE', 'iso3': 'REU', 'name': 'RÃ©union (Fr.)'},
 {'id': 723, 'iso2': 'SH', 'iso3': 'SHN', 'name': 'Saint Helena (U.K.)'},
 {'id': 646, 'iso2': 'KN', 'iso3': 'KNA', 'name': 'Saint Kitts and Nevis'},
 {'id': 691, 'iso2': 'LC', 'iso3': 'LCA', 'name': 'Saint Lucia'},
 {'id': 709,
  'iso2': 'VC',
  'iso3': 'VCT',
  'name': 'Saint Vincent and the Grenadines'},
 {'id': 647, 'iso2': 'WS', 'iso3': 'WSM', 'name': 'Samoa'},
 {'id': 705, 'iso2': 'SM', 'iso3': 'SMR', 'name': 'San Marino'},
 {'id': 649, 'iso2': 'SA', 'iso3': 'SAU', 'name': 'Saudi Arabia'},
 {'id': 559, 'iso2': 'SN', 'iso3': 'SEN', 'name': 'Senegal'},
 {'id': 713, 'iso2': 'RS', 'iso3': 'SRB', 'name': 'Serbia'},
 {'id': 651, 'iso2': 'SC', 'iso3': 'SYC', 'name': 'Seychelles'},
 {'id': 558, 'iso2': 'SL', 'iso3': 'SLE', 'name': 'Sierra Leone'},
 {'id': 652, 'iso2': 'SG', 'iso3': 'SGP', 'name': 'Singapore'},
 {'id': 503, 'iso2': 'SK', 'iso3': 'SVK', 'name': 'Slovak Republic'},
 {'id': 653, 'iso2': 'SI', 'iso3': 'SVN', 'name': 'Slovenia'},
 {'id': 654, 'iso2': 'SB', 'iso3': 'SLB', 'name': 'Solomon Islands'},
 {'id': 536, 'iso2': 'SO', 'iso3': 'SOM', 'name': 'Somalia'},
 {'id': 545, 'iso2': 'ZA', 'iso3': 'ZAF', 'name': 'South Africa'},
 {'id': 655, 'iso2': 'ES', 'iso3': 'ESP', 'name': 'Spain'},
 {'id': 471, 'iso2': 'LK', 'iso3': 'LKA', 'name': 'Sri Lanka'},
 {'id': 526, 'iso2': 'SD', 'iso3': 'SDN', 'name': 'Sudan'},
 {'id': 568, 'iso2': 'SR', 'iso3': 'SUR', 'name': 'Suriname'},
 {'id': 719, 'iso2': 'SJ', 'iso3': 'SJM', 'name': 'Svalbard (Nor.)'},
 {'id': 658, 'iso2': 'SZ', 'iso3': 'SWZ', 'name': 'Swaziland'},
 {'id': 659, 'iso2': 'SE', 'iso3': 'SWE', 'name': 'Sweden'},
 {'id': 660, 'iso2': 'CH', 'iso3': 'CHE', 'name': 'Switzerland'},
 {'id': 510, 'iso2': 'SY', 'iso3': 'SYR', 'name': 'Syrian Arab Republic'},
 {'id': 707,
  'iso2': 'ST',
  'iso3': 'STP',
  'name': 'SÃ£o TomÃ© and PrÃ\xadncipe'},
 {'id': 476, 'iso2': 'TW', 'iso3': 'TWN', 'name': 'Taiwan'},
 {'id': 662, 'iso2': 'TJ', 'iso3': 'TJK', 'name': 'Tajikistan'},
 {'id': 663, 'iso2': 'TZ', 'iso3': 'TZA', 'name': 'Tanzania'},
 {'id': 480, 'iso2': 'TH', 'iso3': 'THA', 'name': 'Thailand'},
 {'id': 734, 'iso2': 'TL', 'iso3': 'TLS', 'name': 'Timor-Leste'},
 {'id': 555, 'iso2': 'TG', 'iso3': 'TGO', 'name': 'Togo'},
 {'id': 726, 'iso2': 'TK', 'iso3': 'TKL', 'name': 'Tokelau (N.Z.)'},
 {'id': 664, 'iso2': 'TO', 'iso3': 'TON', 'name': 'Tonga'},
 {'id': 665, 'iso2': 'TT', 'iso3': 'TTO', 'name': 'Trinidad and Tobago'},
 {'id': 522, 'iso2': 'TN', 'iso3': 'TUN', 'name': 'Tunisia'},
 {'id': 490, 'iso2': 'TR', 'iso3': 'TUR', 'name': 'Turkey'},
 {'id': 489, 'iso2': 'TM', 'iso3': 'TKM', 'name': 'Turkmenistan'},
 {'id': 731,
  'iso2': 'TC',
  'iso3': 'TCA',
  'name': 'Turks and Caicos Islands (U.K.)'},
 {'id': 708, 'iso2': 'TV', 'iso3': 'TUV', 'name': 'Tuvalu'},
 {'id': 710,
  'iso2': 'VI',
  'iso3': 'VIR',
  'name': 'U.S. Virgin Islands (U.S.)'},
 {'id': 533, 'iso2': 'UG', 'iso3': 'UGA', 'name': 'Uganda'},
 {'id': 493, 'iso2': 'UA', 'iso3': 'UKR', 'name': 'Ukraine'},
 {'id': 666, 'iso2': 'AE', 'iso3': 'ARE', 'name': 'United Arab Emirates'},
 {'id': 667, 'iso2': 'GB', 'iso3': 'GBR', 'name': 'United Kingdom'},
 {'id': 668, 'iso2': 'US', 'iso3': 'USA', 'name': 'United States'},
 {'id': 570, 'iso2': 'UY', 'iso3': 'URY', 'name': 'Uruguay'},
 {'id': 486, 'iso2': 'UZ', 'iso3': 'UZB', 'name': 'Uzbekistan'},
 {'id': 669, 'iso2': 'VU', 'iso3': 'VUT', 'name': 'Vanuatu'},
 {'id': 566, 'iso2': 'VE', 'iso3': 'VEN', 'name': 'Venezuela'},
 {'id': 670, 'iso2': 'VN', 'iso3': 'VNM', 'name': 'Vietnam'},
 {'id': 724, 'iso2': 'UM', 'iso3': 'UMI', 'name': 'Wake Island (U.S.)'},
 {'id': 725, 'iso2': 'WF', 'iso3': 'WLF', 'name': 'Wallis and Futuna (Fr.)'},
 {'id': 711, 'iso2': 'PS', 'iso3': 'PSE', 'name': 'West Bank and Gaza'},
 {'id': 512, 'iso2': 'YE', 'iso3': 'YEM', 'name': 'Yemen, Republic of'},
 {'id': 541, 'iso2': 'ZM', 'iso3': 'ZMB', 'name': 'Zambia'},
 {'id': 540, 'iso2': 'ZW', 'iso3': 'ZWE', 'name': 'Zimbabwe'},
 {'id': 496, 'iso2': 'RO', 'iso3': 'ROU', 'name': 'romania'},
 {'id': 498, 'iso2': 'CS', 'iso3': 'SCG', 'name': 'serbia and montenegro'}]

In [ ]:
# make iso:country_name dictionary to add the country name column
isos = {}
for i in range(len(country_codes)):
  isos[country_codes[i]['iso3']] = country_codes[i]['name']

In [ ]:
# adding country name column
temperature['country'] = temperature['iso'].map(isos)

In [ ]:
temp_iso = set(temperature['iso'].unique())

In [ ]:
precipitation = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/precipitation_iso3.csv')

In [ ]:
countries = precipitation.columns[1:]

In [ ]:
precipitation = pd.melt(precipitation, id_vars=['year'], value_vars=countries, var_name='iso', value_name='precipitation')

In [ ]:
precipitation.head(3)

   year  iso  precipitation
0  1901  AFG      19.954466
1  1902  AFG      18.801144
2  1903  AFG      23.728622

In [ ]:
precipitation['country'] = precipitation['iso'].map(isos)

In [ ]:
ppt_iso = set(precipitation['iso'].unique())

In [ ]:
# check if there are any iso codes not in both datasets
temp_iso.symmetric_difference(ppt_iso)

set()

In [ ]:
weather = temperature.merge(precipitation, on=['year', 'iso'], how='outer')

In [ ]:
weather['country_x'].fillna(weather['country_y'], inplace=True)

In [ ]:
weather.drop(columns=['country_y'], inplace=True)

In [ ]:
weather.rename(columns={'country_x':'country'}, inplace=True)

In [ ]:
weather[(weather['iso'] == 'ROM')]

       year  iso  temperature  country  precipitation
19824  1901  ROM     9.215595  Romania      54.282800
19825  1902  ROM     8.389345  Romania      48.508987
19826  1903  ROM     9.500536  Romania      42.776012
19827  1904  ROM     8.901487  Romania      39.530773
19828  1905  ROM     9.126190  Romania      44.678930
...     ...  ...          ...      ...            ...
19931  2008  ROM    10.774226  Romania      49.906906
19932  2009  ROM    10.781309  Romania      48.722023
19933  2010  ROM    10.492812  Romania      67.033330
19934  2011  ROM    10.075417  Romania      38.604324
19935  2012  ROM    10.799427  Romania      49.469112

[112 rows x 5 columns]

In [ ]:
weather[(weather['iso'] == 'ROU')]

       year  iso  temperature  country  precipitation
26768  1901  ROU     9.215595  romania      54.282800
26769  1902  ROU     8.389345  romania      48.508987
26770  1903  ROU     9.500536  romania      42.776012
26771  1904  ROU     8.901487  romania      39.530773
26772  1905  ROU     9.126190  romania      44.678930
...     ...  ...          ...      ...            ...
26875  2008  ROU    10.774226  romania      49.906906
26876  2009  ROU    10.781309  romania      48.722023
26877  2010  ROU    10.492812  romania      67.033330
26878  2011  ROU    10.075417  romania      38.604324
26879  2012  ROU    10.799427  romania      49.469112

[112 rows x 5 columns]

In [ ]:
weather.shape

(26992, 5)

In [ ]:
# delete all 'ROM' rows since they are repeated + rename romania to Romania.
weather.drop(index=weather[(weather['iso'] == 'ROM')].index, inplace=True)

In [ ]:
weather['country'].replace({'romania': 'Romania'}, inplace=True)

In [ ]:
weather.shape

(26880, 5)

In [ ]:
weather.to_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/weather.csv', index=False)

In [ ]:
disasters = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/natural_disasters.csv')

In [ ]:
disasters.head(3)

   year  iso     country  ... continent number_of_disasters  total_human_affected
0  1900  CPV  Cabo Verde  ...    Africa                   1               11000.0
1  1900  IND       India  ...      Asia                   1             1250000.0
2  1900  JAM     Jamaica  ...  Americas                   2                 330.0

[3 rows x 7 columns]

In [ ]:
dis_iso = set(disasters['iso'].unique())

In [ ]:
wea_iso = set(weather['iso'].unique())

In [ ]:
wea_iso.symmetric_difference(dis_iso)

{'ABW',
 'AND',
 'ATF',
 'AZO',
 'BLM',
 'CCK',
 'CSK',
 'CXR',
 'DDR',
 'DFR',
 'ESH',
 'FLK',
 'FRO',
 'GGY',
 'GIB',
 'GRL',
 'IOT',
 'JEY',
 'LIE',
 'MAF',
 'MCO',
 'MLT',
 'MYT',
 'NFK',
 'NRU',
 'PCN',
 'SJM',
 'SMR',
 'SPI',
 'SSD',
 'SUN',
 'SXM',
 'UMI',
 'XRK',
 'XXX',
 'YMD',
 'YMN',
 'YUG'}

In [ ]:
wea_iso.difference(dis_iso)

{'ABW',
 'AND',
 'ATF',
 'CCK',
 'CXR',
 'ESH',
 'FLK',
 'FRO',
 'GGY',
 'GIB',
 'GRL',
 'IOT',
 'JEY',
 'LIE',
 'MCO',
 'MLT',
 'MYT',
 'NFK',
 'NRU',
 'PCN',
 'SJM',
 'SMR',
 'UMI',
 'XRK',
 'XXX'}

In [ ]:
dis_iso.difference(wea_iso)

{'AZO',
 'BLM',
 'CSK',
 'DDR',
 'DFR',
 'MAF',
 'SPI',
 'SSD',
 'SUN',
 'SXM',
 'YMD',
 'YMN',
 'YUG'}

In [ ]:
disasters[disasters['iso'] == 'YUG']['year'].unique()

array([1943, 1963, 1964, 1965, 1967, 1968, 1969, 1972, 1979, 1980, 1981,
       1983, 1985, 1986, 1988, 1990])

In [ ]:
weather[weather['iso'] == 'GBR']

       year  iso  temperature         country  precipitation
25312  1901  GBR     8.163601  United Kingdom      89.739784
25313  1902  GBR     7.798388  United Kingdom      84.223150
25314  1903  GBR     8.028578  United Kingdom     119.318470
25315  1904  GBR     8.073899  United Kingdom      91.663480
25316  1905  GBR     8.185888  United Kingdom      89.656570
...     ...  ...          ...             ...            ...
25419  2008  GBR     9.148782  United Kingdom     116.024880
25420  2009  GBR     9.309748  United Kingdom     114.085570
25421  2010  GBR     8.206399  United Kingdom      90.668750
25422  2011  GBR     9.608892  United Kingdom     106.080400
25423  2012  GBR     8.891592  United Kingdom     118.431990

[112 rows x 5 columns]

In [ ]:
weather[weather['iso'] == 'IND']

       year  iso  temperature country  precipitation
10976  1901  IND    23.736393   India      78.794870
10977  1902  IND    23.920109   India      84.403305
10978  1903  IND    23.434696   India      91.743270
10979  1904  IND    23.456589   India      80.097960
10980  1905  IND    23.266140   India      78.166790
...     ...  ...          ...     ...            ...
11083  2008  IND    24.211040   India      91.581900
11084  2009  IND    24.915022   India      80.215410
11085  2010  IND    23.926294   India     107.658775
11086  2011  IND    23.369070   India      94.529160
11087  2012  IND    23.309038   India      92.322510

[112 rows x 5 columns]

In [ ]:
disasters[disasters['iso'] == 'GBR']

      year  iso  ... number_of_disasters total_human_affected
484   1952  GBR  ...                   2               4034.0
817   1966  GBR  ...                   1                140.0
917   1968  GBR  ...                   1                720.0
1099  1972  GBR  ...                   1                  0.0
1259  1976  GBR  ...                   1                  0.0
1310  1977  GBR  ...                   1                  6.0
1581  1981  GBR  ...                   1                 12.0
1720  1983  GBR  ...                   1                 17.0
1800  1984  GBR  ...                   2                 64.0
1876  1985  GBR  ...                   1                178.0
1943  1986  GBR  ...                   1                  0.0
2032  1987  GBR  ...                   1                 20.0
2210  1989  GBR  ...                   1                 13.0
2297  1990  GBR  ...                   8                 83.0
2392  1991  GBR  ...                   2                 48.0
2569  1993  GBR  ...                   2                604.0
2660  1994  GBR  ...                   2                707.0
2758  1995  GBR  ...                   1                  9.0
2853  1996  GBR  ...                   1              12005.0
2966  1997  GBR  ...                   3                 15.0
3083  1998  GBR  ...                   4             253340.0
3207  1999  GBR  ...                   3                541.0
3343  2000  GBR  ...                   6              21560.0
3469  2001  GBR  ...                   3                281.0
3593  2002  GBR  ...                   6                769.0
3729  2003  GBR  ...                   1                301.0
3853  2004  GBR  ...                   1               1008.0
3987  2005  GBR  ...                   4               3011.0
4237  2007  GBR  ...                   5             374728.0
4369  2008  GBR  ...                   3               3308.0
4493  2009  GBR  ...                   3               4135.0
4612  2010  GBR  ...                   2                  0.0
4849  2012  GBR  ...                   5               3793.0
4963  2013  GBR  ...                   5               5573.0
5071  2014  GBR  ...                   2              18545.0
5186  2015  GBR  ...                   2              63603.0
5419  2017  GBR  ...                   1                 70.0
5543  2018  GBR  ...                   2                  4.0
5675  2019  GBR  ...                   3                106.0
5794  2020  GBR  ...                   3               3038.0

[40 rows x 7 columns]

In [ ]:
# rename United Kingdom of Great Britain and Northern Ireland (the) to United Kingdom
disasters['country'].replace({'United Kingdom of Great Britain and Northern Ireland (the)': 'United Kingdom'}, inplace=True)

In [ ]:
disasters[disasters['iso'] == 'ROM']

Empty DataFrame
Columns: [year, iso, country, region, continent, number_of_disasters, total_human_affected]
Index: []

In [ ]:
disasters[disasters['iso'] == 'SUN']

      year  iso  ... number_of_disasters total_human_affected
14    1902  SUN  ...                   1             129674.0
119   1917  SUN  ...                   1            2500000.0
143   1921  SUN  ...                   1            6200000.0
162   1923  SUN  ...                   2           18000023.0
400   1946  SUN  ...                   1                400.0
426   1948  SUN  ...                   1             110000.0
440   1949  SUN  ...                   2              15500.0
490   1952  SUN  ...                   1                  0.0
574   1956  SUN  ...                   1                  0.0
665   1961  SUN  ...                   1                145.0
845   1966  SUN  ...                   1             100010.0
1192  1974  SUN  ...                   1                 13.0
1288  1976  SUN  ...                   1                  0.0
1613  1981  SUN  ...                   2              12000.0
1677  1982  SUN  ...                   2                586.0
1763  1983  SUN  ...                   4              15000.0
1835  1984  SUN  ...                   4              20500.0
1911  1985  SUN  ...                   4              18109.0
1984  1986  SUN  ...                   2             230061.0
2079  1987  SUN  ...                   4              36694.0
2167  1988  SUN  ...                   2            1667000.0
2250  1989  SUN  ...                   5              22940.0
2340  1990  SUN  ...                   8              47783.0
2439  1991  SUN  ...                   8             298867.0

[24 rows x 7 columns]

In [ ]:
# replace SUN to RUS
disasters['iso'].replace({'SUN': 'RUS'}, inplace=True)

In [ ]:
master_df = disasters.merge(weather, on=['year', 'iso'], how='outer')

In [ ]:
master_df.head(3)

   year  iso   country_x  ... temperature country_y  precipitation
0  1900  CPV  Cabo Verde  ...         NaN       NaN            NaN
1  1900  IND       India  ...         NaN       NaN            NaN
2  1900  JAM     Jamaica  ...         NaN       NaN            NaN

[3 rows x 10 columns]

In [ ]:
# fill missing countries from `country_x` column and delete `country_x`
master_df['country_x'] = master_df['country_x'].fillna(master_df['country_y'])

In [ ]:
master_df.drop(columns=['country_y'], inplace=True)
master_df.rename(columns={'country_x': 'country'}, inplace=True)

In [ ]:
land = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/land.csv', index_col=0)

In [ ]:
land.head(3)

          Area  Year  Cropland  Country_Area  Cropland_pct  iso
0  Afghanistan  1961    7700.0       65286.0      0.117943  AFG
1  Afghanistan  1962    7760.0       65286.0      0.118862  AFG
2  Afghanistan  1963    7810.0       65286.0      0.119627  AFG

In [ ]:
land.columns = land.columns.str.lower()

In [ ]:
land[land['iso'] == 'GBR']

                                                    area  ...  iso
11444  United Kingdom of Great Britain and Northern I...  ...  GBR
11445  United Kingdom of Great Britain and Northern I...  ...  GBR
11446  United Kingdom of Great Britain and Northern I...  ...  GBR
11447  United Kingdom of Great Britain and Northern I...  ...  GBR
11448  United Kingdom of Great Britain and Northern I...  ...  GBR
11449  United Kingdom of Great Britain and Northern I...  ...  GBR
11450  United Kingdom of Great Britain and Northern I...  ...  GBR
11451  United Kingdom of Great Britain and Northern I...  ...  GBR
11452  United Kingdom of Great Britain and Northern I...  ...  GBR
11453  United Kingdom of Great Britain and Northern I...  ...  GBR
11454  United Kingdom of Great Britain and Northern I...  ...  GBR
11455  United Kingdom of Great Britain and Northern I...  ...  GBR
11456  United Kingdom of Great Britain and Northern I...  ...  GBR
11457  United Kingdom of Great Britain and Northern I...  ...  GBR
11458  United Kingdom of Great Britain and Northern I...  ...  GBR
11459  United Kingdom of Great Britain and Northern I...  ...  GBR
11460  United Kingdom of Great Britain and Northern I...  ...  GBR
11461  United Kingdom of Great Britain and Northern I...  ...  GBR
11462  United Kingdom of Great Britain and Northern I...  ...  GBR
11463  United Kingdom of Great Britain and Northern I...  ...  GBR
11464  United Kingdom of Great Britain and Northern I...  ...  GBR
11465  United Kingdom of Great Britain and Northern I...  ...  GBR
11466  United Kingdom of Great Britain and Northern I...  ...  GBR
11467  United Kingdom of Great Britain and Northern I...  ...  GBR
11468  United Kingdom of Great Britain and Northern I...  ...  GBR
11469  United Kingdom of Great Britain and Northern I...  ...  GBR
11470  United Kingdom of Great Britain and Northern I...  ...  GBR
11471  United Kingdom of Great Britain and Northern I...  ...  GBR
11472  United Kingdom of Great Britain and Northern I...  ...  GBR
11473  United Kingdom of Great Britain and Northern I...  ...  GBR
11474  United Kingdom of Great Britain and Northern I...  ...  GBR
11475  United Kingdom of Great Britain and Northern I...  ...  GBR
11476  United Kingdom of Great Britain and Northern I...  ...  GBR
11477  United Kingdom of Great Britain and Northern I...  ...  GBR
11478  United Kingdom of Great Britain and Northern I...  ...  GBR
11479  United Kingdom of Great Britain and Northern I...  ...  GBR
11480  United Kingdom of Great Britain and Northern I...  ...  GBR
11481  United Kingdom of Great Britain and Northern I...  ...  GBR
11482  United Kingdom of Great Britain and Northern I...  ...  GBR
11483  United Kingdom of Great Britain and Northern I...  ...  GBR
11484  United Kingdom of Great Britain and Northern I...  ...  GBR
11485  United Kingdom of Great Britain and Northern I...  ...  GBR
11486  United Kingdom of Great Britain and Northern I...  ...  GBR
11487  United Kingdom of Great Britain and Northern I...  ...  GBR
11488  United Kingdom of Great Britain and Northern I...  ...  GBR
11489  United Kingdom of Great Britain and Northern I...  ...  GBR
11490  United Kingdom of Great Britain and Northern I...  ...  GBR
11491  United Kingdom of Great Britain and Northern I...  ...  GBR
11492  United Kingdom of Great Britain and Northern I...  ...  GBR
11493  United Kingdom of Great Britain and Northern I...  ...  GBR
11494  United Kingdom of Great Britain and Northern I...  ...  GBR
11495  United Kingdom of Great Britain and Northern I...  ...  GBR
11496  United Kingdom of Great Britain and Northern I...  ...  GBR
11497  United Kingdom of Great Britain and Northern I...  ...  GBR
11498  United Kingdom of Great Britain and Northern I...  ...  GBR
11499  United Kingdom of Great Britain and Northern I...  ...  GBR
11500  United Kingdom of Great Britain and Northern I...  ...  GBR
11501  United Kingdom of Great Britain and Northern I...  ...  GBR
11502  United Kingdom of Great Britain and Northern I...  ...  GBR

[59 rows x 6 columns]

In [ ]:
# rename United Kingdom of Great Britain and Northern Ireland (the) to United Kingdom
land['area'].replace({'United Kingdom of Great Britain and Northern Ireland (the)': 'United Kingdom'}, inplace=True)

In [ ]:
land[land['iso'] == 'ROM']

Empty DataFrame
Columns: [area, year, cropland, country_area, cropland_pct, iso]
Index: []

In [ ]:
land[land['iso'] == 'ROU']

         area  year  cropland  country_area  cropland_pct  iso
9058  Romania  1961   10393.0       23839.0      0.435966  ROU
9059  Romania  1962   10491.0       23839.0      0.440077  ROU
9060  Romania  1963   10475.0       23839.0      0.439406  ROU
9061  Romania  1964   10496.0       23839.0      0.440287  ROU
9062  Romania  1965   10475.0       23839.0      0.439406  ROU
9063  Romania  1966   10502.0       23839.0      0.440539  ROU
9064  Romania  1967   10526.0       23839.0      0.441545  ROU
9065  Romania  1968   10560.0       23839.0      0.442972  ROU
9066  Romania  1969   10544.0       23839.0      0.442300  ROU
9067  Romania  1970   10512.0       23839.0      0.440958  ROU
9068  Romania  1971   10506.0       23839.0      0.440706  ROU
9069  Romania  1972   10488.0       23839.0      0.439951  ROU
9070  Romania  1973   10426.0       23839.0      0.437351  ROU
9071  Romania  1974   10469.0       23839.0      0.439154  ROU
9072  Romania  1975   10500.0       23839.0      0.440455  ROU
9073  Romania  1976   10518.0       23839.0      0.441210  ROU
9074  Romania  1977   10534.0       23839.0      0.441881  ROU
9075  Romania  1978   10542.0       23839.0      0.442217  ROU
9076  Romania  1979   10481.0       23839.0      0.439658  ROU
9077  Romania  1980   10497.0       23839.0      0.440329  ROU
9078  Romania  1981   10509.0       23839.0      0.440832  ROU
9079  Romania  1982   10524.0       23839.0      0.441461  ROU
9080  Romania  1983   10555.0       23839.0      0.442762  ROU
9081  Romania  1984   10574.0       23839.0      0.443559  ROU
9082  Romania  1985   10622.0       23839.0      0.445572  ROU
9083  Romania  1986   10638.0       23839.0      0.446244  ROU
9084  Romania  1987   10686.0       23839.0      0.448257  ROU
9085  Romania  1988   10707.0       23839.0      0.449138  ROU
9086  Romania  1989   10053.0       23839.0      0.421704  ROU
9087  Romania  1990   10041.0       23839.0      0.421201  ROU
9088  Romania  1991   10020.0       23839.0      0.420320  ROU
9089  Romania  1992    9960.0       23839.0      0.417803  ROU
9090  Romania  1993    9941.0       23839.0      0.417006  ROU
9091  Romania  1994    9926.0       23839.0      0.416377  ROU
9092  Romania  1995    9907.0       23839.0      0.415580  ROU
9093  Romania  1996    9882.0       23839.0      0.414531  ROU
9094  Romania  1997    9898.0       23839.0      0.415202  ROU
9095  Romania  1998    9843.0       23839.0      0.412895  ROU
9096  Romania  1999    9845.0       23839.0      0.412979  ROU
9097  Romania  2000    9908.0       23839.0      0.415621  ROU
9098  Romania  2001    9862.0       23839.0      0.413692  ROU
9099  Romania  2002    9859.0       23839.0      0.413566  ROU
9100  Romania  2003    9842.0       23839.0      0.412853  ROU
9101  Romania  2004    9344.0       23839.0      0.391963  ROU
9102  Romania  2005    9495.0       23839.0      0.398297  ROU
9103  Romania  2006    9408.0       23839.0      0.394647  ROU
9104  Romania  2007    9136.0       23839.0      0.383238  ROU
9105  Romania  2008    9184.0       23839.0      0.385251  ROU
9106  Romania  2009    9249.0       23839.0      0.387978  ROU
9107  Romania  2010    9609.0       23839.0      0.403079  ROU
9108  Romania  2011    9439.0       23839.0      0.395948  ROU
9109  Romania  2012    9244.0       23839.0      0.387768  ROU
9110  Romania  2013    9188.0       23840.0      0.385403  ROU
9111  Romania  2014    9203.0       23840.0      0.386032  ROU
9112  Romania  2015    9203.0       23840.0      0.386032  ROU
9113  Romania  2016    9000.0       23840.0      0.377517  ROU
9114  Romania  2017    8958.0       23840.0      0.375755  ROU
9115  Romania  2018    9126.0       23840.0      0.382802  ROU
9116  Romania  2019    9378.0       23840.0      0.393372  ROU

In [ ]:
land[land['iso'] == 'SUN']

       area  year  cropland  country_area  cropland_pct  iso
11739  USSR  1961  239800.0     2241237.0      0.106994  SUN
11740  USSR  1962  240300.0     2241237.0      0.107218  SUN
11741  USSR  1963  238500.0     2241237.0      0.106414  SUN
11742  USSR  1964  237100.0     2241237.0      0.105790  SUN
11743  USSR  1965  236550.0     2241237.0      0.105544  SUN
11744  USSR  1966  233900.0     2241237.0      0.104362  SUN
11745  USSR  1967  233550.0     2241237.0      0.104206  SUN
11746  USSR  1968  233100.0     2241237.0      0.104005  SUN
11747  USSR  1969  233400.0     2241237.0      0.104139  SUN
11748  USSR  1970  233000.0     2241237.0      0.103960  SUN
11749  USSR  1971  232800.0     2241237.0      0.103871  SUN
11750  USSR  1972  232600.0     2241237.0      0.103782  SUN
11751  USSR  1973  232300.0     2241237.0      0.103648  SUN
11752  USSR  1974  232900.0     2241237.0      0.103916  SUN
11753  USSR  1975  232400.0     2241237.0      0.103693  SUN
11754  USSR  1976  232500.0     2241237.0      0.103737  SUN
11755  USSR  1977  232600.0     2241237.0      0.103782  SUN
11756  USSR  1978  232000.0     2241237.0      0.103514  SUN
11757  USSR  1979  231400.0     2241237.0      0.103247  SUN
11758  USSR  1980  231517.0     2241237.0      0.103299  SUN
11759  USSR  1981  231700.0     2241237.0      0.103380  SUN
11760  USSR  1982  231750.0     2241237.0      0.103403  SUN
11761  USSR  1983  231900.0     2241237.0      0.103470  SUN
11762  USSR  1984  231686.0     2241237.0      0.103374  SUN
11763  USSR  1985  231811.0     2241237.0      0.103430  SUN
11764  USSR  1986  231925.0     2241237.0      0.103481  SUN
11765  USSR  1987  232062.0     2241237.0      0.103542  SUN
11766  USSR  1988  231540.0     2241237.0      0.103309  SUN
11767  USSR  1989  229930.0     2241237.0      0.102591  SUN
11768  USSR  1990  228920.0     2241237.0      0.102140  SUN
11769  USSR  1991  228920.0     2241237.0      0.102140  SUN

In [ ]:
# change iso code SUN to RUS 
land['iso'].replace({'SUN': 'RUS'}, inplace=True)

In [ ]:
master_df = master_df.merge(land, on=['year', 'iso'], how='outer')

In [ ]:
master_df.head(3)

   year  iso     country  ... cropland country_area  cropland_pct
0  1900  CPV  Cabo Verde  ...      NaN          NaN           NaN
1  1900  IND       India  ...      NaN          NaN           NaN
2  1900  JAM     Jamaica  ...      NaN          NaN           NaN

[3 rows x 13 columns]

In [ ]:
master_df['country'] = master_df['country'].fillna(master_df['area'])

In [ ]:
master_df.drop(columns=['area'], inplace=True)

In [ ]:
master_df.head(3)

   year  iso     country  ... cropland country_area  cropland_pct
0  1900  CPV  Cabo Verde  ...      NaN          NaN           NaN
1  1900  IND       India  ...      NaN          NaN           NaN
2  1900  JAM     Jamaica  ...      NaN          NaN           NaN

[3 rows x 12 columns]

In [ ]:
population = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/Population_withISO.csv', sep='\t', index_col=0)

In [ ]:
population.head(3)

  Country or Area  Year(s) Variant      Value  ISO
0     Afghanistan     2020  Medium  38928.346  AFG
1     Afghanistan     2019  Medium  38041.754  AFG
2     Afghanistan     2018  Medium  37171.921  AFG

In [ ]:
population.columns = population.columns.str.lower()
population.rename(columns={'year(s)': 'year', 'value': 'population'}, inplace=True)

In [ ]:
population[population['iso'] == 'GBR']

      country or area  year variant  population  iso
18886  United Kingdom  2020  Medium   67886.011  GBR
18887  United Kingdom  2019  Medium   67530.172  GBR
18888  United Kingdom  2018  Medium   67141.684  GBR
18889  United Kingdom  2017  Medium   66727.461  GBR
18890  United Kingdom  2016  Medium   66297.944  GBR
...               ...   ...     ...         ...  ...
18952  United Kingdom  1954  Medium   50890.915  GBR
18953  United Kingdom  1953  Medium   50750.976  GBR
18954  United Kingdom  1952  Medium   50651.280  GBR
18955  United Kingdom  1951  Medium   50601.935  GBR
18956  United Kingdom  1950  Medium   50616.014  GBR

[71 rows x 5 columns]

In [ ]:
population[population['iso'] == 'ROM']

      country or area  year variant  population  iso
14910         Romania  2020  Medium   19237.691  ROM
14911         Romania  2019  Medium   19364.557  ROM
14912         Romania  2018  Medium   19506.114  ROM
14913         Romania  2017  Medium   19653.969  ROM
14914         Romania  2016  Medium   19796.285  ROM
...               ...   ...     ...         ...  ...
14976         Romania  1954  Medium   17243.818  ROM
14977         Romania  1953  Medium   17005.717  ROM
14978         Romania  1952  Medium   16764.904  ROM
14979         Romania  1951  Medium   16512.664  ROM
14980         Romania  1950  Medium   16236.296  ROM

[71 rows x 5 columns]

In [ ]:
population[population['iso'] == 'ROU']

Empty DataFrame
Columns: [country or area, year, variant, population, iso]
Index: []

In [ ]:
# change iso code ROM to ROU
population['iso'].replace({'ROM': 'ROU'}, inplace=True)

In [ ]:
population[population['iso'] == 'SUN']

Empty DataFrame
Columns: [country or area, year, variant, population, iso]
Index: []

In [ ]:
master_df = master_df.merge(population, on=['year', 'iso'], how='outer')

In [ ]:
master_df['country'].fillna(master_df['country or area'], inplace=True)
master_df.drop(columns=['country or area'], inplace=True)

In [ ]:
master_df.rename(columns={'country': 'country_or_area'}, inplace=True)

In [ ]:
rice_df = pd.read_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/rice_production.csv')

In [ ]:
rice_df.head(3)

   iso      country  year  rice_production_in_tonnes
0  AFG  Afghanistan  1961                   212773.0
1  AFG  Afghanistan  1962                   212773.0
2  AFG  Afghanistan  1963                   212773.0

In [ ]:
rice_df[rice_df['iso'] == 'GBR']

Empty DataFrame
Columns: [iso, country, year, rice_production_in_tonnes]
Index: []

In [ ]:
rice_df[rice_df['iso'] == 'ROM']

Empty DataFrame
Columns: [iso, country, year, rice_production_in_tonnes]
Index: []

In [ ]:
rice_df[rice_df['iso'] == 'SUN']

      iso country  year  rice_production_in_tonnes
6658  SUN    USSR  1961                   153077.0
6659  SUN    USSR  1962                   168751.0
6660  SUN    USSR  1963                   233450.0
6661  SUN    USSR  1964                   292146.0
6662  SUN    USSR  1965                   361848.0
6663  SUN    USSR  1966                   441554.0
6664  SUN    USSR  1967                   555611.0
6665  SUN    USSR  1968                   659663.0
6666  SUN    USSR  1969                   686343.0
6667  SUN    USSR  1970                   793730.0
6668  SUN    USSR  1971                   886443.0
6669  SUN    USSR  1972                  1021844.0
6670  SUN    USSR  1973                  1093880.0
6671  SUN    USSR  1974                  1186593.0
6672  SUN    USSR  1975                  1247290.0
6673  SUN    USSR  1976                  1240620.0
6674  SUN    USSR  1977                  1374020.0
6675  SUN    USSR  1978                  1309988.0
6676  SUN    USSR  1979                  1488077.0
6677  SUN    USSR  1980                  1730198.0
6678  SUN    USSR  1981                  1543438.0
6679  SUN    USSR  1982                  1538102.0
6680  SUN    USSR  1983                  1620810.0
6681  SUN    USSR  1984                  1693513.0
6682  SUN    USSR  1985                  1600800.0
6683  SUN    USSR  1986                  1604135.0
6684  SUN    USSR  1987                  1619476.0
6685  SUN    USSR  1988                  1732199.0
6686  SUN    USSR  1989                  1502751.0
6687  SUN    USSR  1990                  1444989.0
6688  SUN    USSR  1991                  1324795.0

In [ ]:
# replace iso code SUN with RUS
rice_df['iso'].replace({'SUN': 'RUS'}, inplace=True)

In [ ]:
master_df = master_df.merge(rice_df, on=['year', 'iso'], how='outer')

In [ ]:
master_df.head(3)

   year  iso country_or_area  ... population country  rice_production_in_tonnes
0  1900  CPV      Cabo Verde  ...        NaN     NaN                        NaN
1  1900  IND           India  ...        NaN     NaN                        NaN
2  1900  JAM         Jamaica  ...        NaN     NaN                        NaN

[3 rows x 16 columns]

In [ ]:
master_df['country_or_area'].fillna(master_df['country'], inplace=True)
master_df.drop(columns=['country'], inplace=True)

In [ ]:
master_df.head(3)

   year  iso country_or_area  ... variant population  rice_production_in_tonnes
0  1900  CPV      Cabo Verde  ...     NaN        NaN                        NaN
1  1900  IND           India  ...     NaN        NaN                        NaN
2  1900  JAM         Jamaica  ...     NaN        NaN                        NaN

[3 rows x 15 columns]

In [ ]:
# we only have data from 1961-2019 for rice production, so I will limit the data to those years
master_df2 = master_df[(master_df['year'] < 2020) & (master_df['year'] > 1960)]

In [ ]:
master_df[master_df['iso'] == 'ROM']

Empty DataFrame
Columns: [year, iso, country_or_area, region, continent, number_of_disasters, total_human_affected, temperature, precipitation, cropland, country_area, cropland_pct, variant, population, rice_production_in_tonnes]
Index: []

In [ ]:
master_df[master_df['iso'] == 'ROU']

       year  iso country_or_area  ... variant population  rice_production_in_tonnes
48     1908  ROU         Romania  ...     NaN        NaN                        NaN
98     1913  ROU         Romania  ...     NaN        NaN                        NaN
190    1926  ROU         Romania  ...     NaN        NaN                        NaN
212    1928  ROU         Romania  ...     NaN        NaN                        NaN
268    1934  ROU         Romania  ...     NaN        NaN                        NaN
...     ...  ...             ...  ...     ...        ...                        ...
27917  1987  ROU         Romania  ...  Medium  23288.400                    77039.0
27918  1988  ROU         Romania  ...  Medium  23393.730                    87777.0
27919  1989  ROU         Romania  ...  Medium  23466.407                    46823.0
27920  1992  ROU         Romania  ...  Medium  23375.822                    25960.0
27921  2011  ROU         Romania  ...  Medium  20336.718                    43529.0

[121 rows x 15 columns]

In [ ]:
# input missing data for number of disastesr and total human affected as 0
master_df2['number_of_disasters'].fillna(0, inplace=True)
master_df2['total_human_affected'].fillna(0, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [ ]:
master_df2.head()

     year  iso country_or_area  ... variant population  rice_production_in_tonnes
651  1961  BGD      Bangladesh  ...  Medium  49362.843                  9622265.0
652  1961  BLZ          Belize  ...  Medium     94.703                      566.0
653  1961  CAN          Canada  ...  Medium  18233.964                        NaN
654  1961  ETH        Ethiopia  ...  Medium  22671.191                        NaN
655  1961  FRA          France  ...  Medium  46266.981                    89171.0

[5 rows x 15 columns]

In [ ]:
rice_df[rice_df['iso'] == 'IRL']

      iso  country  year  rice_production_in_tonnes
3327  IRL  Ireland  2018                        0.0
3328  IRL  Ireland  2019                        0.0

In [ ]:
master_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18554 entries, 651 to 34134
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       18554 non-null  int64
 1   iso                        14306 non-null  object
 2   country_or_area            18554 non-null  object
 3   region                     5108 non-null   object
 4   continent                  5108 non-null   object
 5   number_of_disasters        18554 non-null  float64
 6   total_human_affected       18554 non-null  float64
 7   temperature                12262 non-null  float64
 8   precipitation              12262 non-null  float64
 9   cropland                   12293 non-null  float64
 10  country_area               12293 non-null  float64
 11  cropland_pct               12293 non-null  float64
 12  variant                    16815 non-null  object
 13  population                 16815 non-null  float64
 14  rice_production_in_tonnes  6823 non-null   float64
dtypes: float64(9), int64(1), object(5)
memory usage: 2.3+ MB

In [ ]:
# drop any rows without an iso code since they are regions rather than countries
master_df2 = master_df2.dropna(subset=['iso'])

In [ ]:
master_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14306 entries, 651 to 34134
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       14306 non-null  int64
 1   iso                        14306 non-null  object
 2   country_or_area            14306 non-null  object
 3   region                     5108 non-null   object
 4   continent                  5108 non-null   object
 5   number_of_disasters        14306 non-null  float64
 6   total_human_affected       14306 non-null  float64
 7   temperature                12262 non-null  float64
 8   precipitation              12262 non-null  float64
 9   cropland                   12293 non-null  float64
 10  country_area               12293 non-null  float64
 11  cropland_pct               12293 non-null  float64
 12  variant                    12567 non-null  object
 13  population                 12567 non-null  float64
 14  rice_production_in_tonnes  6823 non-null   float64
dtypes: float64(9), int64(1), object(5)
memory usage: 1.7+ MB

In [ ]:
tmp_df = master_df2.dropna(subset=['rice_production_in_tonnes'])

In [ ]:
tmp_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6823 entries, 651 to 28920
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       6823 non-null   int64
 1   iso                        6823 non-null   object
 2   country_or_area            6823 non-null   object
 3   region                     3911 non-null   object
 4   continent                  3911 non-null   object
 5   number_of_disasters        6823 non-null   float64
 6   total_human_affected       6823 non-null   float64
 7   temperature                5927 non-null   float64
 8   precipitation              5927 non-null   float64
 9   cropland                   6823 non-null   float64
 10  country_area               6823 non-null   float64
 11  cropland_pct               6823 non-null   float64
 12  variant                    6476 non-null   object
 13  population                 6476 non-null   float64
 14  rice_production_in_tonnes  6823 non-null   float64
dtypes: float64(9), int64(1), object(5)
memory usage: 852.9+ KB

In [ ]:
tmp_df[tmp_df['precipitation'].isna()]

       year  iso country_or_area  ... variant population  rice_production_in_tonnes
719    1963  YUG      Yugoslavia  ...     NaN        NaN                    15541.0
753    1964  YUG      Yugoslavia  ...     NaN        NaN                    16875.0
800    1965  YUG      Yugoslavia  ...     NaN        NaN                    16408.0
902    1967  YUG      Yugoslavia  ...     NaN        NaN                    13473.0
951    1968  YUG      Yugoslavia  ...     NaN        NaN                    11873.0
...     ...  ...             ...  ...     ...        ...                        ...
28916  1989  YUG    Yugoslav SFR  ...     NaN        NaN                    18326.0
28917  1991  YUG    Yugoslav SFR  ...     NaN        NaN                    25013.0
28918  2015  ZMB          Zambia  ...  Medium  15879.361                    17018.0
28919  2016  ZMB          Zambia  ...  Medium  16363.458                    17792.0
28920  2018  ZMB          Zambia  ...  Medium  17351.708                    28723.0

[896 rows x 15 columns]

In [ ]:
master_df.to_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/master_df.csv', index=False)
master_df2.to_csv('/content/drive/MyDrive/DS4A-W_Team25/Colab_Files/data/global_data/master_df_clean.csv', index=False)